### ISSUE TITLE
Observing Array<T> crashes in Swift 1.2 (Xcode 6.3 Beta)

### ISSUE THREAD

**Issue by harenbrs** [slazyk/Observable-Swift#10]
In a Playground, the following code will result in a runtime error EXC_BAD_ACCESS. In a compiled Swift app, it crashes both the app and Xcode (if debugging), or just the app (if running a release configuration). This makes it tricky to pinpoint the source of this issue.

Since observing arrays used to work previous to this update to Swift, we are probably dealing with a bug in the (reportedly newly improved) compiler. I would file a bug report with Apple, but I have no idea which language feature is actually misbehaving. Perhaps it will be a little more obvious to you, slazyk?

```swift
import Observable

class Test {
    var vals = Observable<[Int]>([])
    
    func put(val: Int) {
        vals.value.append(val)
    }
}


let t = Test()

t.vals.afterChange.add {
    println($0.newValue)
}

t.put(2)
```

**Comment by slazyk** [comment]
Can you still reproduce in the latest beta?

**Comment by harenbrs** [comment]
Nope! Observing Arrays now works now without any errors or crashes.
