### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by AlwaysBCoding** [slazyk/Observable-Swift#11]
In your documentation to install the framework it says:

"and then add Observable.framework to frameworks for your target."

What is that supposed to mean? Do I just drag the .framework file into the frameworks folder? Or do I need to link it through the configuration UI? Can you be more clear about how someone is to go about doing that? I can't figure it out.

**Comment by slazyk** [comment]
Go to the configuration for your target and add it to Embedded Binaries.
