### ISSUE TITLE
Code signing error when installing via Carthage

### ISSUE THREAD

**Issue by bradleyayers** [slazyk/Observable-Swift#18]
I am having a problem when installing via Carthage.

The error is

> CodeSign error: code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 9.1'

I think ideally the unit tests wouldn't even be built when installing via Carthage, but failing that perhaps the unit test target needs to have code signing enabled?

**Comment by bradleyayers** [comment]
Modifying the project to change the Observable-iOS Tests target to use code signing fixed the issue for me when building with carthage:

![image](https://cloud.githubusercontent.com/assets/105820/11168364/770cdf76-8be0-11e5-9fac-a634e08aa4bf.png)

**Comment by AdamRitenauer** [comment]
I've submitted a PR to fix this issue https://github.com/slazyk/Observable-Swift/pull/25
