### ISSUE TITLE
Update minimumosversion to 8.0 to fix usage with Carthage

### ISSUE THREAD

**Issue by bradleyayers** [slazyk/Observable-Swift#23]
It's currently not possible to submit an app that uses Observable-Swift via Carthage, because when the the framework is built via Carthage minimumosversion is set to 7.0, however it must be 8.0 or higher. setting to 8.0 is sensible because iOS 8.0 is the first version to support frameworks.

A similar [issue was opened for Alamofire](https://github.com/Alamofire/Alamofire/issues/352).

**Comment by nacrossweb** [comment]
:+1:

**Comment by masgharneya** [comment]
Any updates on this issue or are people just using the fork by @bradleyayers?

I can understand why we wouldn't want to raise the minimum os version since this will work fine with iOS7. Maybe there can be two separate targets?

**Comment by bradleyayers** [comment]
I actually switched over to RxSwift and have enjoyed that.

**Comment by slazyk** [comment]
This seems obsolete
