### ISSUE TITLE
Support Xcode 8 and Swift 3 / Swift 2.3

### ISSUE THREAD

**Issue by marchy** [slazyk/Observable-Swift#31]
iOS 10 is out!

When are the plans to support Swift 2.3/3.0 and Xcode 8?
Due to the nature of the Swift runtime ALL libraries in a project must support it for the app to update to it - which means this library is blocking us from building against the iOS 10 SDK.

Thanks  =)

**Comment by Vaseltior** [comment]
Here is a swift3 compatible version https://github.com/Vaseltior/Observable-Swift

**Comment by marchy** [comment]
@Vaseltior fantastic Vaseltior! Have you tested this out with Swift 2.3 by any chance?

**Comment by Vaseltior** [comment]
Nope, sorry
Le ven. 16 sept. 2016 à 21:21, Marcel Bradea <notifications@github.com> a
écrit :

**Comment by leogeng** [comment]
@Vaseltior , Does it wok ok in Xcode 8 and swift-3 project? I find it still not works and i install it by cocoa pod

**Comment by marchy** [comment]
@leogeng This has been working for us ever since @Vaseltior pushed up his changes (thanks Samuel!). What issues are you running into?

**Comment by Vaseltior** [comment]
You're welcome guys. I'm glad That it works for you.
Le mar. 14 mars 2017 à 16:13, Marcel Bradea <notifications@github.com> a
écrit :

**Comment by leogeng** [comment]
I got the following error when building my project
observable-Swift/Observable.framework/Observable compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64

**Comment by slazyk** [comment]
Sorry for the delay. I just pushed two updates, 0.6.1 for Xcode 8's legacy support of Swift 2.3, and 0.7.0 for actual Swift 3.

Sorry I did not accept the pull request but it changed some formatting and the diff wasn't clean.
