### ISSUE TITLE
Issue setting before/afterChange handlers

### ISSUE THREAD

**Issue by marcelvanworkum** [slazyk/Observable-Swift#33]
Hey, I'm trying to get the library up and running, however when I go to add a handler an observable like so:

```swift
var ob = Observable(0)
ob.beforeChange += { print("foo") }
```

I get the following error:  `Left side of mutating operator isn't mutable: 'beforeChange' setter is inaccessible`

I am using version 0.7.0 through cocoapods, with Xcode 8.3.

**Comment by slazyk** [comment]
Hey,

Sorry for that. It would seem the compiler gets confused and picks a wrong overload with such a lambda. `beforeChange` is a reference type, it's not like it has to be mutable. If you instead do this it works:
```swift
var ob = Observable(0)
ob.beforeChange += { _ in print("foo") }
```

I'll look whether any of the overloads are actually wrong, or consider reverting access level change for the setters if that mitigates the issue.

Let me know if you have other examples that don't work.

**Comment by marcelvanworkum** [comment]
Awesome, that seems to do the trick! Thanks for the help @slazyk
