### ISSUE TITLE
Compilation error using cocoapods in Xcode 9.0

### ISSUE THREAD

**Issue by sewil** [slazyk/Observable-Swift#36]
- "Type alias cannot be declared public because its underlying type uses an internal type" at PairObservable row 14.
- "Property cannot be declared public because its type uses an internal type" at PairObservable row 22.

**Comment by sewil** [comment]
Also using Swift 4.

**Comment by marchy** [comment]
Any ETA on an Xcode 9 / Swift 4 update?

**Comment by Francescu** [comment]
It seems that a PR is ready for this issue =>  #37
